# Generated by Django 4.2.6 on 2023-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(to='m2mapp.student'),
        ),
    ]
