# Generated by Django 4.2.6 on 2023-10-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2mapp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student',
            new_name='students',
        ),
    ]
