# Generated by Django 4.2.6 on 2023-10-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2mapp', '0005_rename_student_teacher_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='students',
        ),
        migrations.RenameModel(
            old_name='teacher',
            new_name='teachers',
        ),
    ]
