# Generated by Django 4.2.6 on 2023-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2mapp', '0006_rename_student_students_rename_teacher_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='students',
            field=models.ManyToManyField(related_name='teachers', to='m2mapp.students'),
        ),
    ]
