# Generated by Django 4.2.6 on 2023-10-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2mapp', '0007_alter_teachers_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2mapp.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2mapp.teachers')),
            ],
        ),
    ]
